using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("OpenMessage.Samples.Core")]
[assembly: InternalsVisibleTo("OpenMessage.Tests")]
[assembly: InternalsVisibleTo("OpenMessage.Apache.Kafka")]
[assembly: InternalsVisibleTo("OpenMessage.AWS.SQS")]
[assembly: InternalsVisibleTo("OpenMessage.AWS.SNS")]
[assembly: InternalsVisibleTo("OpenMessage.Azure.EventHubs")]
[assembly: InternalsVisibleTo("OpenMessage.Azure.ServiceBus")]
[assembly: InternalsVisibleTo("OpenMessage.EventStore")]
[assembly: InternalsVisibleTo("OpenMessage.NATS")]
[assembly: InternalsVisibleTo("OpenMessage.RabbitMq")]
[assembly: InternalsVisibleTo("OpenMessage.Redis")]
[assembly: InternalsVisibleTo("OpenMessage.Serializer.JsonDotNet")]
